name: Greetings

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
  pull_request_target:
    types: [closed]

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Greet New Issue Contributors
        if: github.event_name == 'issues'
        uses: actions/first-interaction@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "@${{ github.actor }} <h1>It's great having you contribute to this project</h1> Thanks for opening this<strong>Issue ðŸ™Œ</strong>, Welcome to <strong>Project Guidance ðŸ’–</strong> We will review everything and get back to you.<br> Make sure to give a star to this repo before making a fork! Thank you :)"

      - name: Greet New PR Contributors
        if: github.event_name == 'pull_request'
        uses: actions/first-interaction@v1.1.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pr-message: "@${{ github.actor }} <h1>It's great having you contribute to this project</h1> Thank you for opening a <strong>Pull Request ðŸ™Œ</strong>, Welcome to <strong>Project Guidance ðŸ’–</strong> We will review everything and get back to you."

  congratulate:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true
    steps:
      - name: Congratulate on every PR merge
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            @${{ github.event.pull_request.user.login }} Hurray, your PR got merged into our Project-Guidance ðŸ¥³. Thanks a bunch. Feel free to take another Issue. ðŸ’–
